In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [50]:
df = pd.read_csv("./new_us_etf_stock.csv")
price_df = df[["Date", "Adj Close"]].copy()
price_df.sort_values(["Date"], inplace=True)
price_df['STD_YM'] = price_df['Date'].map(lambda x: datetime.strptime(x, '%Y-%m-%d').strftime("%Y-%m"))
month_list = price_df['STD_YM'].unique()
monthly_df = pd.DataFrame()
for m in month_list:
    monthly_df = monthly_df.append(
        price_df.loc[price_df[price_df['STD_YM'] == m].index[-1], :]
    )

monthly_df.set_index(['Date'], inplace=True)
monthly_df['1M BF Adj Close'] = monthly_df.shift(1)['Adj Close']
monthly_df['12M BF Adj Close'] = monthly_df.shift(12)['Adj Close']
monthly_df.fillna(0, inplace=True)
monthly_df.head(15)

            Adj Close   STD_YM  1M BF Adj Close  12M BF Adj Close
Date
1972-08-31   0.023047  1972-08         0.000000          0.000000
1972-09-29   0.020977  1972-09         0.023047          0.000000
1972-10-31   0.023227  1972-10         0.020977          0.000000
1972-11-30   0.023227  1972-11         0.023227          0.000000
1972-12-29   0.024848  1972-12         0.023227          0.000000
1973-01-31   0.021337  1973-01         0.024848          0.000000
1973-02-28   0.022327  1973-02         0.021337          0.000000
1973-03-30   0.016385  1973-03         0.022327          0.000000
1973-04-30   0.016115  1973-04         0.016385          0.000000
1973-05-31   0.015845  1973-05         0.016115          0.000000
1973-06-29   0.010894  1973-06         0.015845          0.000000
1973-07-31   0.017286  1973-07         0.010894          0.000000
1973-08-31   0.015215  1973-08         0.017286          0.023047
1973-09-28   0.016205  1973-09         0.015215          0.020977
1973-10-31   0.016925  1973-10         0.016205          0.023227

In [51]:
book = price_df.copy()
book.set_index(['Date'], inplace=True)
book['trade'] = ''
book.head()

            Adj Close   STD_YM trade
Date
1972-08-25   0.023768  1972-08
1972-08-28   0.023678  1972-08
1972-08-29   0.023408  1972-08
1972-08-30   0.023408  1972-08
1972-08-31   0.023047  1972-08

In [54]:
ticker = 'SPY'
for x in monthly_df.index:
    signal = ''
    momentum = monthly_df.loc[x, '1M BF Adj Close'] / monthly_df.loc[x, '12M BF Adj Close'] - 1.
    if (momentum > 0.) and (momentum != np.inf) and (momentum != -np.inf):
        signal = f"buy {ticker}"
    else:
        pass
    print(f"날짜: {x}\t모멘텀: {momentum}\t시그널: {signal}")
    book.loc[x, 'trade'] = signal

print(book)

/var/folders/xw/w771g5jd07x9kcp7x8s8_pwh0000gn/T/ipykernel_47209/3207230458.py:4: RuntimeWarning: invalid value encountered in double_scalars
  momentum = monthly_df.loc[x, '1M BF Adj Close'] / monthly_df.loc[x, '12M BF Adj Close'] - 1.
/var/folders/xw/w771g5jd07x9kcp7x8s8_pwh0000gn/T/ipykernel_47209/3207230458.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  momentum = monthly_df.loc[x, '1M BF Adj Close'] / monthly_df.loc[x, '12M BF Adj Close'] - 1.

날짜: 1972-08-31	모멘텀: nan	시그널:
날짜: 1972-09-29	모멘텀: inf	시그널:
날짜: 1972-10-31	모멘텀: inf	시그널:
날짜: 1972-11-30	모멘텀: inf	시그널:
날짜: 1972-12-29	모멘텀: inf	시그널:
날짜: 1973-01-31	모멘텀: inf	시그널:
날짜: 1973-02-28	모멘텀: inf	시그널:
날짜: 1973-03-30	모멘텀: inf	시그널:
날짜: 1973-04-30	모멘텀: inf	시그널:
날짜: 1973-05-31	모멘텀: inf	시그널:
날짜: 1973-06-29	모멘텀: inf	시그널:
날짜: 1973-07-31	모멘텀: inf	시그널:
날짜: 1973-08-31	모멘텀: -0.24996745780361873	시그널:
날짜: 1973-09-28	모멘텀: -0.27468179434618867	시그널:
날짜: 1973-10-31	모멘텀: -0.30232057519266375	시그널:
날짜: 1973-11-30	모멘텀: -0.27132216816635824	시그널:
날짜: 1973-12-31	모멘텀: -0.5507083065035414	시그널:
날짜: 1974-01-31	모멘텀: -0.5485307212822796	시그널:
날짜: 1974-02-28	모멘텀: -0.3871097773995611	시그널:
날짜: 1974-03-29	모멘텀: -0.26371681415929205	시그널:
날짜: 1974-04-30	모멘텀: -0.29953459509773506	시그널:
날짜: 1974-05-31	모멘텀: -0.28191858630482813	시그널:
날짜: 1974-06-28	모멘텀: 0.12731778960895923	시그널: buy SPY
날짜: 1974-07-31	모멘텀: -0.185005206525512	시그널:
날짜: 1974-08-30	모멘텀: -0.07407163982911602	시그널:
날짜: 1974-09-30	모멘텀: -0.2644245603208887	시그널:
날짜: 1974-10-31	모멘텀: -0.39521418020679466	시그널:
날짜: 1974-11-29	모멘텀: -0.19670369043353642	시그널:
날짜: 1974-12-31	모멘텀: -0.24769023149589942	시그널:
날짜: 1975-01-31	모멘텀: -0.4968576439637533	시그널:
날짜: 1975-02-28	모멘텀: -0.09888925729442966	시그널:
날짜: 1975-03-31	모멘텀: -0.09319631467044642	시그널:
날짜: 1975-04-30	모멘텀: 0.2759711724380385	시그널: buy SPY
날짜: 1975-05-30	모멘텀: 0.012213989088836419	시그널: buy SPY
날짜: 1975-06-30	모멘텀: 0.08205565019875083	시그널: buy SPY
날짜: 1975-07-31	모멘텀: 0.25752413401476426	시그널: buy SPY
날짜: 1975-08-29	모멘텀: 0.4938758389261746	시그널: buy SPY
날짜: 1975-09-30	모멘텀: 0.6686205549042596	시그널: buy SPY
날짜: 1975-10-31	모멘텀: 0.9879571810883139	시그널: buy SPY
날짜: 1975-11-28	모멘텀: 1.8366220505036566	시그널: buy SPY
날짜: 1975-12-31	모멘텀: 2.170660856935367	시그널: buy SPY
날짜: 1976-01-30	모멘텀: 0.7597277159414957	시그널: buy SPY
날짜: 1976-02-27	모멘텀: 0.9401133255177805	시그널: buy SPY
날짜: 1976-03-31	모멘텀: 0.5184598429535747	시그널: buy SPY
날짜: 1976-04-30	모멘텀: 0.9224519346794304	시그널: buy SPY
날짜: 1976-05-28	모멘텀: 0.37621359223300965	시그널: buy SPY
날짜: 1976-06-30	모멘텀: 0.1327048995258524	시그널: buy SPY
날짜: 1976-07-30	모멘텀: 0.12860111192227786	시그널: buy SPY
날짜: 1976-08-31	모멘텀: 0.026873536299765632	시그널: buy SPY
날짜: 1976-09-30	모멘텀: 0.20922144940542964	시그널: buy SPY
날짜: 1976-10-29	모멘텀: 0.10351705015323254	시그널: buy SPY
날짜: 1976-11-30	모멘텀: -0.04461749885478694	시그널:
날짜: 1976-12-31	모멘텀: 0.17626764244641913	시그널: buy SPY
날짜: 1977-01-31	모멘텀: 0.14426708293468948	시그널: buy SPY
날짜: 1977-02-28	모멘텀: -0.07729643910183703	시그널:
날짜: 1977-03-31	모멘텀: -0.16415599631768352	시그널:
날짜: 1977-04-29	모멘텀: -0.028695362028695492	시그널:
날짜: 1977-05-31	모멘텀: -0.12174216375143276	시그널:
날짜: 1977-06-30	모멘텀: -0.031746031746031744	시그널:
날짜: 1977-07-29	모멘텀: 0.21797137807172584	시그널: buy SPY
날짜: 1977-08-31	모멘텀: -0.0005102514147879988	시그널:
날짜: 1977-09-30	모멘텀: 0.006656380868415246	시그널: buy SPY
날짜: 1977-10-31	모멘텀: 0.20435366321442272	시그널: buy SPY
날짜: 1977-11-30	모멘텀: 0.10803484134743568	시그널: buy SPY
날짜: 1977-12-30	모멘텀: 0.20577363140292193	시그널: buy SPY
날짜: 1978-01-31	모멘텀: 0.47446044933877385	시그널: buy SPY
날짜: 1978-02-28	모멘텀: 0.40881101376720896	시그널: buy SPY
날짜: 1978-03-31	모멘텀: 0.4082544044756342	시그널: buy SPY
날짜: 1978-04-28	모멘텀: 0.5805719473445301	시그널: buy SPY
날짜: 1978-05-31	모멘텀: 0.7750655223803895	시그널: buy SPY
날짜: 1978-06-30	모멘텀: 0.6690852916393597	시그널: buy SPY
날짜: 1978-07-31	모멘텀: 0.6153060750916601	시그널: buy SPY
날짜: 1978-08-31	모멘텀: 0.5974776668418287	시그널: buy SPY
날짜: 1978-09-29	모멘텀: 0.6153754279799346	시그널: buy SPY
날짜: 1978-10-31	모멘텀: 0.6604901135041912	시그널: buy SPY
날짜: 1978-11-30	모멘텀: 0.23875912408759126	시그널: buy SPY
날짜: 1978-12-29	모멘텀: 0.14413843691651107	시그널: buy SPY
날짜: 1979-01-31	모멘텀: 0.20905440460537994	시그널: buy SPY
날짜: 1979-02-28	모멘텀: 0.17915388904376917	시그널: buy SPY
날짜: 1979-03-30	모멘텀: 0.2415637564618036	시그널: buy SPY
날짜: 1979-04-30	모멘텀: 0.05321212472134573	시그널: buy SPY
날짜: 1979-05-31	모멘텀: 0.06764829617164492	시그널: buy SPY
날짜: 1979-06-29	모멘텀: 0.09909495762103138	시그널: buy SPY
날짜: 1979-07-31	모멘텀: 0.04131030701754379	시그널: buy SPY
날짜: 1979-08-31	모멘텀: -0.035982747997535536	시그널:
날짜: 1979-09-28	모멘텀: 0.24726455882708165	시그널: buy SPY
날짜: 1979-10-31	모멘텀: 0.41588592304519456	시그널: buy SPY
날짜: 1979-11-30	모멘텀: 0.29613871484773435	시그널: buy SPY
날짜: 1979-12-31	모멘텀: 0.5509346343757349	시그널: buy SPY
날짜: 1980-01-31	모멘텀: 0.4845878771758727	시그널: buy SPY
날짜: 1980-02-29	모멘텀: 0.5562527107127369	시그널: buy SPY
날짜: 1980-03-31	모멘텀: 0.3289535171390088	시그널: buy SPY
날짜: 1980-04-30	모멘텀: 0.13502508734599528	시그널: buy SPY
날짜: 1980-05-30	모멘텀: 0.287996026559314	시그널: buy SPY
날짜: 1980-06-30	모멘텀: 0.3668886724405718	시그널: buy SPY
날짜: 1980-07-31	모멘텀: 0.4912437683753037	시그널: buy SPY
날짜: 1980-08-29	모멘텀: 0.2914907626166776	시그널: buy SPY
날짜: 1980-09-30	모멘텀: 0.5292146989054893	시그널: buy SPY
날짜: 1980-10-31	모멘텀: 0.7122557726465364	시그널: buy SPY
날짜: 1980-11-28	모멘텀: 0.4576361121112773	시그널: buy SPY
날짜: 1980-12-31	모멘텀: 0.7055380817772823	시그널: buy SPY
날짜: 1981-01-30	모멘텀: 8.053304349441687	시그널: buy SPY
날짜: 1981-02-27	모멘텀: 7.343709924295702	시그널: buy SPY
날짜: 1981-03-31	모멘텀: 1.237993843590159	시그널: buy SPY
날짜: 1981-04-30	모멘텀: 6.100302409125043	시그널: buy SPY
날짜: 1981-05-29	모멘텀: 1.278734303982744	시그널: buy SPY
날짜: 1981-06-30	모멘텀: 1.0350248585633466	시그널: buy SPY
날짜: 1981-07-31	모멘텀: 0.7484030589293746	시그널: buy SPY
날짜: 1981-08-31	모멘텀: 3.8574383257813887	시그널: buy SPY
날짜: 1981-09-30	모멘텀: 0.4380219549346078	시그널: buy SPY
날짜: 1981-10-30	모멘텀: 0.5086975740398867	시그널: buy SPY
날짜: 1981-11-30	모멘텀: 0.442574349876278	시그널: buy SPY
날짜: 1981-12-31	모멘텀: -0.7200354624483865	시그널:
날짜: 1982-01-29	모멘텀: -0.21681272233722126	시그널:
날짜: 1982-02-26	모멘텀: 0.36256553977889694	시그널: buy SPY
날짜: 1982-03-31	모멘텀: -0.2551030616940936	시그널:
날짜: 1982-04-30	모멘텀: 1.0364939444392798	시그널: buy SPY
날짜: 1982-05-28	모멘텀: 0.7743190989275754	시그널: buy SPY
날짜: 1982-06-30	모멘텀: 0.7144621401188669	시그널: buy SPY
날짜: 1982-07-30	모멘텀: -0.5376353724879405	시그널:
날짜: 1982-08-31	모멘텀: 0.5534726153733769	시그널: buy SPY
날짜: 1982-09-30	모멘텀: 0.690433104113886	시그널: buy SPY
날짜: 1982-10-29	모멘텀: 0.7958719678948816	시그널: buy SPY
날짜: 1982-11-30	모멘텀: 1.6560108488491423	시그널: buy SPY
날짜: 1982-12-31	모멘텀: 0.44067598108417805	시그널: buy SPY
날짜: 1983-01-31	모멘텀: 1.3688257081271442	시그널: buy SPY
날짜: 1983-02-28	모멘텀: 1.2397292339808281	시그널: buy SPY
날짜: 1983-03-31	모멘텀: 0.27903386454183265	시그널: buy SPY
날짜: 1983-04-29	모멘텀: 1.8644079062943635	시그널: buy SPY
날짜: 1983-05-31	모멘텀: 2.6071392840706724	시그널: buy SPY
날짜: 1983-06-30	모멘텀: 1.7285555030474873	시그널: buy SPY
날짜: 1983-07-29	모멘텀: 3.1021824872007384	시그널: buy SPY
날짜: 1983-08-31	모멘텀: 1.6214265323600179	시그널: buy SPY
날짜: 1983-09-30	모멘텀: 1.3963795115314088	시그널: buy SPY
날짜: 1983-10-31	모멘텀: -0.08866981478363822	시그널:
날짜: 1983-11-30	모멘텀: -0.2901963541449246	시그널:
날짜: 1983-12-30	모멘텀: -0.0678293021303592	시그널:
날짜: 1984-01-31	모멘텀: -0.16042216358839045	시그널:
날짜: 1984-02-29	모멘텀: 0.1466988539760412	시그널: buy SPY
날짜: 1984-03-30	모멘텀: -0.3786982444682765	시그널:
날짜: 1984-04-30	모멘텀: -0.41977073787678754	시그널:
날짜: 1984-05-31	모멘텀: -0.005220279821209317	시그널:
날짜: 1984-06-29	모멘텀: -0.3989772056421337	시그널:
날짜: 1984-07-31	모멘텀: -0.2641626477909148	시그널:
날짜: 1984-08-31	모멘텀: -0.03461377933363152	시그널:
날짜: 1984-09-28	모멘텀: 0.6859072394421648	시그널: buy SPY
날짜: 1984-10-31	모멘텀: 0.11049788742203592	시그널: buy SPY
날짜: 1984-11-30	모멘텀: 0.8267253735344764	시그널: buy SPY
날짜: 1984-12-31	모멘텀: -0.27880039507946486	시그널:
날짜: 1985-01-31	모멘텀: 0.1767701919594351	시그널: buy SPY
날짜: 1985-02-28	모멘텀: 0.6035210910633437	시그널: buy SPY
날짜: 1985-03-29	모멘텀: 0.436523813279605	시그널: buy SPY
날짜: 1985-04-30	모멘텀: -0.29482062820306787	시그널:
날짜: 1985-05-31	모멘텀: -0.2765962012068214	시그널:
날짜: 1985-06-28	모멘텀: -0.3443394107247151	시그널:
날짜: 1985-07-31	모멘텀: -0.499453734953368	시그널:
날짜: 1985-08-30	모멘텀: -0.5928093480271963	시그널:
날짜: 1985-09-30	모멘텀: 1.1903596524725235	시그널: buy SPY
날짜: 1985-10-31	모멘텀: -0.5768352205802108	시그널:
날짜: 1985-11-29	모멘텀: -0.24747317547989867	시그널:
날짜: 1985-12-31	모멘텀: 1.1633836683658747	시그널: buy SPY
날짜: 1986-01-31	모멘텀: -0.47734022357801353	시그널:
날짜: 1986-02-28	모멘텀: 0.6540264174110673	시그널: buy SPY
날짜: 1986-03-31	모멘텀: 0.12994182181903358	시그널: buy SPY
날짜: 1986-04-30	모멘텀: 0.32941261769562113	시그널: buy SPY
날짜: 1986-05-30	모멘텀: 4.140757758968158	시그널: buy SPY
날짜: 1986-06-30	모멘텀: 1.0555590139442232	시그널: buy SPY
날짜: 1986-07-31	모멘텀: 1.2598453333098059	시그널: buy SPY
날짜: 1986-08-29	모멘텀: -0.9093354712275076	시그널:
날짜: 1986-09-30	모멘텀: -0.6832046812749004	시그널:
날짜: 1986-10-31	모멘텀: 0.7986568853426785	시그널: buy SPY
날짜: 1986-11-28	모멘텀: -0.892332845767738	시그널:
날짜: 1986-12-31	모멘텀: 3.918151403350725	시그널: buy SPY
날짜: 1987-01-30	모멘텀: 0.5391549086095433	시그널: buy SPY
날짜: 1987-02-27	모멘텀: 1.2199995517931073	시그널: buy SPY
날짜: 1987-03-31	모멘텀: 1.477878453586524	시그널: buy SPY
날짜: 1987-04-30	모멘텀: 0.5094431490126403	시그널: buy SPY
날짜: 1987-05-29	모멘텀: -0.5079117517905544	시그널:
날짜: 1987-06-30	모멘텀: -0.4375790607967768	시그널:
날짜: 1987-07-31	모멘텀: 31.27120119024226	시그널: buy SPY
날짜: 1987-08-31	모멘텀: 15.559778794598994	시그널: buy SPY
날짜: 1987-09-30	모멘텀: 2.232944009733438	시그널: buy SPY
날짜: 1987-10-30	모멘텀: 25.745429394336686	시그널: buy SPY
날짜: 1987-11-30	모멘텀: -0.2840323548391481	시그널:
날짜: 1987-12-31	모멘텀: -0.3810122884421461	시그널:
날짜: 1988-01-29	모멘텀: -0.657745009091586	시그널:
날짜: 1988-02-29	모멘텀: -0.7211384448230633	시그널:
날짜: 1988-03-31	모멘텀: -0.8458027495653646	시그널:
날짜: 1988-04-29	모멘텀: 3.4245453566373323	시그널: buy SPY
날짜: 1988-05-31	모멘텀: 3.092454912741055	시그널: buy SPY
날짜: 1988-06-30	모멘텀: 4.782235426849582	시그널: buy SPY
날짜: 1988-07-29	모멘텀: 0.8352262806636279	시그널: buy SPY
날짜: 1988-08-31	모멘텀: -0.8076395328235311	시그널:
날짜: 1988-09-30	모멘텀: -0.17260131318359606	시그널:
날짜: 1988-10-31	모멘텀: -0.7638381254152862	시그널:
날짜: 1988-11-30	모멘텀: -0.7413412646124737	시그널:
날짜: 1988-12-30	모멘텀: -0.12903249592602684	시그널:
날짜: 1989-01-31	모멘텀: 3.179799306146025	시그널: buy SPY
날짜: 1989-02-28	모멘텀: 7.211667570581122	시그널: buy SPY
날짜: 1989-03-31	모멘텀: -0.7413899371561257	시그널:
날짜: 1989-04-28	모멘텀: -0.7885111049480564	시그널:
날짜: 1989-05-31	모멘텀: 1.0483870712967285	시그널: buy SPY
날짜: 1989-06-30	모멘텀: 13.458655488808825	시그널: buy SPY
날짜: 1989-07-31	모멘텀: 3.033538163653599	시그널: buy SPY
날짜: 1989-08-31	모멘텀: 0.49300694570464	시그널: buy SPY
날짜: 1989-09-29	모멘텀: 111.86328732094596	시그널: buy SPY
날짜: 1989-10-31	모멘텀: 0.3979631406004449	시그널: buy SPY
날짜: 1989-11-30	모멘텀: 4.739294603701383	시그널: buy SPY
날짜: 1989-12-29	모멘텀: 1.8000545900254754	시그널: buy SPY
날짜: 1990-01-31	모멘텀: -0.82156311033679	시그널:
날짜: 1990-02-28	모멘텀: 9.821753921245653	시그널: buy SPY
날짜: 1990-03-30	모멘텀: 2.998255534167469	시그널: buy SPY
날짜: 1990-04-30	모멘텀: -0.8673767342631307	시그널:
날짜: 1990-05-31	모멘텀: -0.9631186738489351	시그널:
날짜: 1990-06-29	모멘텀: 0.010880028002216768	시그널: buy SPY
날짜: 1990-07-31	모멘텀: 0.5039435079441954	시그널: buy SPY
날짜: 1990-08-31	모멘텀: -0.42181819748167526	시그널:
날짜: 1990-09-28	모멘텀: 11.910788951179631	시그널: buy SPY
날짜: 1990-10-31	모멘텀: 8.014672215059727	시그널: buy SPY
날짜: 1990-11-30	모멘텀: -0.8045912602484583	시그널:
날짜: 1990-12-31	모멘텀: 9.745014644553468	시그널: buy SPY
날짜: 1991-01-31	모멘텀: 0.4645198285205032	시그널: buy SPY
날짜: 1991-02-28	모멘텀: 0.6473317586170582	시그널: buy SPY
날짜: 1991-03-28	모멘텀: -0.7127506728958041	시그널:
날짜: 1991-04-30	모멘텀: 13.856982383814588	시그널: buy SPY
날짜: 1991-05-31	모멘텀: 4.228184771138372	시그널: buy SPY
날짜: 1991-06-28	모멘텀: 3.009402496750667	시그널: buy SPY
날짜: 1991-07-31	모멘텀: -0.9400588550858496	시그널:
날짜: 1991-08-30	모멘텀: -0.75067570363981	시그널:
날짜: 1991-09-30	모멘텀: -0.3465178736159059	시그널:
날짜: 1991-10-31	모멘텀: 10.817960913748585	시그널: buy SPY
날짜: 1991-11-29	모멘텀: 0.5612218917275484	시그널: buy SPY
날짜: 1991-12-31	모멘텀: 0.6355227644630246	시그널: buy SPY
날짜: 1992-01-31	모멘텀: 0.025284370779798726	시그널: buy SPY
날짜: 1992-02-28	모멘텀: 0.7385549787071612	시그널: buy SPY
날짜: 1992-03-31	모멘텀: 0.20000001165897352	시그널: buy SPY
날짜: 1992-04-30	모멘텀: -0.7197237470352416	시그널:
날짜: 1992-05-29	모멘텀: -0.9143116793734789	시그널:
날짜: 1992-06-30	모멘텀: 0.7499065387634147	시그널: buy SPY
날짜: 1992-07-31	모멘텀: 0.3056037821765294	시그널: buy SPY
날짜: 1992-08-31	모멘텀: -0.8244842548294221	시그널:
날짜: 1992-09-30	모멘텀: 0.20992669941903497	시그널: buy SPY
날짜: 1992-10-30	모멘텀: 0.29770111508512875	시그널: buy SPY
날짜: 1992-11-30	모멘텀: 0.26434967956777555	시그널: buy SPY
날짜: 1992-12-31	모멘텀: 5.122557714862598	시그널: buy SPY
날짜: 1993-01-29	모멘텀: 9.402487077542506	시그널: buy SPY
날짜: 1993-02-26	모멘텀: -0.9054586972855918	시그널:
날짜: 1993-03-31	모멘텀: 0.05537995514781757	시그널: buy SPY
날짜: 1993-04-30	모멘텀: 11.642717840705203	시그널: buy SPY
날짜: 1993-05-28	모멘텀: 14.038564850881869	시그널: buy SPY
날짜: 1993-06-30	모멘텀: 18.18609753623531	시그널: buy SPY
날짜: 1993-07-30	모멘텀: 5.044405321790566	시그널: buy SPY
날짜: 1993-08-31	모멘텀: -0.9078750988482261	시그널:
날짜: 1993-09-30	모멘텀: -0.8215028429252138	시그널:
날짜: 1993-10-29	모멘텀: 1.9159910431310103	시그널: buy SPY
날짜: 1993-11-30	모멘텀: 1.8118532932528724	시그널: buy SPY
날짜: 1993-12-31	모멘텀: 0.5286219925379374	시그널: buy SPY
날짜: 1994-01-31	모멘텀: 14.425356848684032	시그널: buy SPY
날짜: 1994-02-28	모멘텀: 12.260049173004319	시그널: buy SPY
날짜: 1994-03-31	모멘텀: -0.9112176928644163	시그널:
날짜: 1994-04-29	모멘텀: -0.929090705433984	시그널:
날짜: 1994-05-31	모멘텀: -0.7025460761758784	시그널:
날짜: 1994-06-30	모멘텀: 2.3883143067414228	시그널: buy SPY
날짜: 1994-07-29	모멘텀: -0.030100617231757942	시그널:
날짜: 1994-08-31	모멘텀: -0.38744985093577067	시그널:
날짜: 1994-09-30	모멘텀: -0.9607434008447181	시그널:
날짜: 1994-10-31	모멘텀: -0.09761626464017514	시그널:
날짜: 1994-11-30	모멘텀: -0.9011585053243003	시그널:
날짜: 1994-12-30	모멘텀: -0.745332713120369	시그널:
날짜: 1995-01-31	모멘텀: 0.17184876542527427	시그널: buy SPY
날짜: 1995-02-28	모멘텀: 3.052365662072904	시그널: buy SPY
날짜: 1995-03-31	모멘텀: 14.012904081843503	시그널: buy SPY
날짜: 1995-04-28	모멘텀: 2.1586006883608775	시그널: buy SPY
날짜: 1995-05-31	모멘텀: -0.9586754781063801	시그널:
날짜: 1995-06-30	모멘텀: 0.5873194006686795	시그널: buy SPY
날짜: 1995-07-31	모멘텀: 7.563741924142722	시그널: buy SPY
날짜: 1995-08-31	모멘텀: 0.2541757352618341	시그널: buy SPY
날짜: 1995-09-29	모멘텀: -0.9487331264560098	시그널:
날짜: 1995-10-31	모멘텀: -0.5901671034357956	시그널:
날짜: 1995-11-30	모멘텀: -0.05867815295105594	시그널:
날짜: 1995-12-29	모멘텀: -0.9590775816673461	시그널:
날짜: 1996-01-31	모멘텀: 4.349621192279784	시그널: buy SPY
날짜: 1996-02-29	모멘텀: -0.762164876570337	시그널:
날짜: 1996-03-29	모멘텀: -0.7263262428918323	시그널:
날짜: 1996-04-30	모멘텀: 2.9111188840659112	시그널: buy SPY
날짜: 1996-05-31	모멘텀: 2.941857766762739	시그널: buy SPY
날짜: 1996-06-28	모멘텀: 2.0593143128601805	시그널: buy SPY
날짜: 1996-07-31	모멘텀: 2.8617609928991876	시그널: buy SPY
날짜: 1996-08-30	모멘텀: 18.265946984185923	시그널: buy SPY
날짜: 1996-09-30	모멘텀: 36.15897304801916	시그널: buy SPY
날짜: 1996-10-31	모멘텀: 2.605338428800152	시그널: buy SPY
날짜: 1996-11-29	모멘텀: 6.5172357998940305	시그널: buy SPY
날짜: 1996-12-31	모멘텀: -0.8245723827664193	시그널:
날짜: 1997-01-31	모멘텀: -0.9040709736522022	시그널:
날짜: 1997-02-28	모멘텀: 0.13663660745520279	시그널: buy SPY
날짜: 1997-03-31	모멘텀: 0.8909096668848253	시그널: buy SPY
날짜: 1997-04-30	모멘텀: 0.8676403031664184	시그널: buy SPY
날짜: 1997-05-30	모멘텀: 0.978536282594479	시그널: buy SPY
날짜: 1997-06-30	모멘텀: -0.9037719069587773	시그널:
날짜: 1997-07-31	모멘텀: -0.5598396375450603	시그널:
날짜: 1997-08-29	모멘텀: -0.9873176215218562	시그널:
날짜: 1997-09-30	모멘텀: -0.9737726290552944	시그널:
날짜: 1997-10-31	모멘텀: 2.5273047734045577	시그널: buy SPY
날짜: 1997-11-28	모멘텀: -0.27987446865357113	시그널:
날짜: 1997-12-31	모멘텀: 18.49782043174897	시그널: buy SPY
날짜: 1998-01-30	모멘텀: 7.1517291649552615	시그널: buy SPY
날짜: 1998-02-27	모멘텀: 0.5661934038917649	시그널: buy SPY
날짜: 1998-03-31	모멘텀: -0.9223370552197261	시그널:
날짜: 1998-04-30	모멘텀: -0.699838271913144	시그널:
날짜: 1998-05-29	모멘텀: 13.69951090279193	시그널: buy SPY
날짜: 1998-06-30	모멘텀: 5.516850025265828	시그널: buy SPY
날짜: 1998-07-31	모멘텀: 0.6392867449106696	시그널: buy SPY
날짜: 1998-08-31	모멘텀: 39.9640816062614	시그널: buy SPY
날짜: 1998-09-30	모멘텀: 1.0698726172930701	시그널: buy SPY
날짜: 1998-10-30	모멘텀: 4.030249444606522	시그널: buy SPY
날짜: 1998-11-30	모멘텀: 0.8874912921783087	시그널: buy SPY
날짜: 1998-12-31	모멘텀: -0.508676663919654	시그널:
날짜: 1999-01-29	모멘텀: 0.8164246781960349	시그널: buy SPY
날짜: 1999-02-26	모멘텀: 51.14547269900927	시그널: buy SPY
날짜: 1999-03-31	모멘텀: -0.9323876405523186	시그널:
날짜: 1999-04-30	모멘텀: -0.8529436884117139	시그널:
날짜: 1999-05-28	모멘텀: -0.9805820654041197	시그널:
날짜: 1999-06-30	모멘텀: 65.15311423793284	시그널: buy SPY
날짜: 1999-07-30	모멘텀: 0.6461538213181637	시그널: buy SPY
날짜: 1999-08-31	모멘텀: 0.39989791941692077	시그널: buy SPY
날짜: 1999-09-30	모멘텀: 1.432008093097211	시그널: buy SPY
날짜: 1999-10-29	모멘텀: 0.3861815696431432	시그널: buy SPY
날짜: 1999-11-30	모멘텀: 1.9341482596411943	시그널: buy SPY
날짜: 1999-12-31	모멘텀: 2.8628429060549667	시그널: buy SPY
날짜: 2000-01-31	모멘텀: -0.9165439863774936	시그널:
날짜: 2000-02-29	모멘텀: 87.92751820193358	시그널: buy SPY
날짜: 2000-03-31	모멘텀: 27.61435846626727	시그널: buy SPY
날짜: 2000-04-28	모멘텀: 71.6980511968182	시그널: buy SPY
날짜: 2000-05-31	모멘텀: -0.07052631578947366	시그널:
날짜: 2000-06-30	모멘텀: 0.052848884319055545	시그널: buy SPY
날짜: 2000-07-31	모멘텀: -0.9642395547239222	시그널:
날짜: 2000-08-31	모멘텀: -0.5958833206030151	시그널:
날짜: 2000-09-29	모멘텀: -0.8855549592801956	시그널:
날짜: 2000-10-31	모멘텀: 0.05873554530623992	시그널: buy SPY
날짜: 2000-11-30	모멘텀: -0.6689712066901601	시그널:
날짜: 2000-12-29	모멘텀: 5.420858478400631	시그널: buy SPY
날짜: 2001-01-31	모멘텀: -0.838792888725808	시그널:
날짜: 2001-02-28	모멘텀: 1.9867442238724569	시그널: buy SPY
날짜: 2001-03-30	모멘텀: -0.16917045042397094	시그널:
날짜: 2001-04-30	모멘텀: -0.9749762718006795	시그널:
날짜: 2001-05-31	모멘텀: -0.9669857904269081	시그널:
날짜: 2001-06-29	모멘텀: 4.092625670981616	시그널: buy SPY
날짜: 2001-07-31	모멘텀: 0.04565750372269228	시그널: buy SPY
날짜: 2001-08-31	모멘텀: 2.2755732712172043	시그널: buy SPY
날짜: 2001-09-28	모멘텀: -0.9109711080332741	시그널:
날짜: 2001-10-31	모멘텀: 0.09713653285152213	시그널: buy SPY
날짜: 2001-11-30	모멘텀: 2.625940590991378	시그널: buy SPY
날짜: 2001-12-31	모멘텀: 1.4988590736801628	시그널: buy SPY
날짜: 2002-01-31	모멘텀: -0.5757591563016089	시그널:
날짜: 2002-02-28	모멘텀: -0.8367589958476389	시그널:
날짜: 2002-03-28	모멘텀: 9.21001493848285	시그널: buy SPY
날짜: 2002-04-30	모멘텀: 26.256578844250058	시그널: buy SPY
날짜: 2002-05-31	모멘텀: 1.3736455138618626	시그널: buy SPY
날짜: 2002-06-28	모멘텀: 1.9063252459003919	시그널: buy SPY
날짜: 2002-07-31	모멘텀: 0.7476925540432344	시그널: buy SPY
날짜: 2002-08-30	모멘텀: 1.5040480984340046	시그널: buy SPY
날짜: 2002-09-30	모멘텀: 0.8733363238054841	시그널: buy SPY
날짜: 2002-10-31	모멘텀: -0.9878845779165134	시그널:
날짜: 2002-11-29	모멘텀: -0.9742279800477496	시그널:
날짜: 2002-12-31	모멘텀: -0.9762086528975045	시그널:
날짜: 2003-01-31	모멘텀: 0.3312190979563072	시그널: buy SPY
날짜: 2003-02-28	모멘텀: 0.5496453900709222	시그널: buy SPY
날짜: 2003-03-31	모멘텀: -0.21273538319816965	시그널:
날짜: 2003-04-30	모멘텀: -0.34294464181346673	시그널:
날짜: 2003-05-30	모멘텀: -0.4739386293571146	시그널:
날짜: 2003-06-30	모멘텀: 2.2175462281732106	시그널: buy SPY
날짜: 2003-07-31	모멘텀: 0.6224288277728367	시그널: buy SPY
날짜: 2003-08-29	모멘텀: -0.6241242704800829	시그널:
날짜: 2003-09-30	모멘텀: 0.5593100970334481	시그널: buy SPY
날짜: 2003-10-31	모멘텀: 18.968213605209456	시그널: buy SPY
날짜: 2003-11-28	모멘텀: 18.575546273851955	시그널: buy SPY
날짜: 2003-12-31	모멘텀: 1.85706743552501	시그널: buy SPY
날짜: 2004-01-30	모멘텀: -0.09018343249427929	시그널:
날짜: 2004-02-27	모멘텀: 0.472577166546601	시그널: buy SPY
날짜: 2004-03-31	모멘텀: 2.240265568948691	시그널: buy SPY
날짜: 2004-04-30	모멘텀: 0.07722713167835082	시그널: buy SPY
날짜: 2004-05-28	모멘텀: -0.4168609068323934	시그널:
날짜: 2004-06-30	모멘텀: -0.475454763215859	시그널:
날짜: 2004-07-30	모멘텀: -0.1587775297243994	시그널:
날짜: 2004-08-31	모멘텀: 26.509439936895095	시그널: buy SPY
날짜: 2004-09-30	모멘텀: 0.8937362758805065	시그널: buy SPY
날짜: 2004-10-29	모멘텀: 1.0229137547786915	시그널: buy SPY
날짜: 2004-11-30	모멘텀: 0.55554192040871	시그널: buy SPY
날짜: 2004-12-31	모멘텀: 3.4110771039823353	시그널: buy SPY
날짜: 2005-01-31	모멘텀: -0.12123017376070744	시그널:
날짜: 2005-02-28	모멘텀: -0.7724163829045289	시그널:
날짜: 2005-03-31	모멘텀: -0.1370125031657231	시그널:
날짜: 2005-04-29	모멘텀: -0.5676249888601729	시그널:
날짜: 2005-05-31	모멘텀: 3.558419835348251	시그널: buy SPY
날짜: 2005-06-30	모멘텀: 1.007828457700986	시그널: buy SPY
날짜: 2005-07-29	모멘텀: -0.530903264691843	시그널:
날짜: 2005-08-31	모멘텀: -0.0549671912635149	시그널:
날짜: 2005-09-30	모멘텀: -0.8472126504634268	시그널:
날짜: 2005-10-31	모멘텀: 0.10873653834111785	시그널: buy SPY
날짜: 2005-11-30	모멘텀: -0.4708630765670674	시그널:
날짜: 2005-12-30	모멘텀: -0.19911659067246334	시그널:
날짜: 2006-01-31	모멘텀: 0.786344591257284	시그널: buy SPY
날짜: 2006-02-28	모멘텀: 0.518068332779207	시그널: buy SPY
날짜: 2006-03-31	모멘텀: 1.661474980111394	시그널: buy SPY
날짜: 2006-04-28	모멘텀: -0.7675679947982523	시그널:
날짜: 2006-05-31	모멘텀: -0.15462191334348552	시그널:
날짜: 2006-06-30	모멘텀: 0.8956859534768773	시그널: buy SPY
날짜: 2006-07-31	모멘텀: -0.6900195218965073	시그널:
날짜: 2006-08-31	모멘텀: 5.081821625682947	시그널: buy SPY

In [53]:
buy = 0.; sell = 0.; current = 0.;
book['return'] = 1.
for idx in book.index:
    # long side
    try:
        if book.loc[idx, 'trade'] == f'buy {ticker}' and book.shift(1).loc[idx, 'trade'] == '':
            buy = book.loc[idx, 'Adj Close']
            print(f"[진입일: {idx}] 진입 가격: {buy}")
        elif book.loc[idx, 'trade'] == f'buy {ticker}' and book.shift(1).loc[idx, 'trade'] == f'buy {ticker}':
            current = book.loc[idx, 'Adj Close']
            rtn = (current - buy) / buy + 1.
            book.loc[idx, 'return'] = rtn
        elif book.loc[idx, 'trade'] == '' and book.shift(1).loc[idx, 'trade'] == f'buy {ticker}':
            sell = book.loc[idx, 'Adj Close']
            rtn= (sell - buy) / buy + 1.
            book.loc[idx, 'return']= rtn
            print(f"[청산일: {idx}] 진입 가격: {buy}\t청산 가격: {sell}\treturn: {rtn}")
        else:
            pass

        if book.loc[idx, 'trade'] == '':
            buy = 0.; sell = 0.; current = 0.;
    except:
        pass

acc_rtn = 1.
for idx in book.index:
    if book.loc[idx, 'trade'] == '' and book.shift(1).loc[idx, 'trade'] == f'buy {ticker}':
        rtn= book.loc[idx, 'return']
        acc_rtn *= rtn
        book.loc[idx:, 'acc_return'] = acc_rtn

print(f"Accumulated return: {acc_rtn}")

[진입일: 1974-06-28] 진입 가격: 0.014088
[청산일: 1974-07-01] 진입 가격: 0.014088	청산 가격: 0.013997	return: 0.9935406019307212
[진입일: 1975-04-30] 진입 가격: 0.012431
[청산일: 1975-05-01] 진입 가격: 0.012431	청산 가격: 0.012431	return: 1.0
[진입일: 1975-05-30] 진입 가격: 0.015244
[청산일: 1975-06-02] 진입 가격: 0.015244	청산 가격: 0.015244	return: 1.0
[진입일: 1975-06-30] 진입 가격: 0.017716
[청산일: 1975-07-01] 진입 가격: 0.017716	청산 가격: 0.01817	return: 1.0256265522691352
[진입일: 1975-07-31] 진입 가격: 0.017807
[청산일: 1975-08-01] 진입 가격: 0.017807	청산 가격: 0.017262	return: 0.9693940585163138
[진입일: 1975-08-29] 진입 가격: 0.01708
[청산일: 1975-09-02] 진입 가격: 0.01708	청산 가격: 0.01708	return: 1.0
[진입일: 1975-09-30] 진입 가격: 0.017828
[청산일: 1975-10-01] 진입 가격: 0.017828	청산 가격: 0.017282	return: 0.9693740183980255
[진입일: 1975-10-31] 진입 가격: 0.020557
[청산일: 1975-11-03] 진입 가격: 0.020557	청산 가격: 0.021285	return: 1.0354137276840005
[진입일: 1975-11-28] 진입 가격: 0.02183
[청산일: 1975-12-01] 진입 가격: 0.02183	청산 가격: 0.022194	return: 1.016674301420064
[진입일: 1975-12-31] 진입 가격: 0.01913
[청산일: 1976-01-02] 진입 가격: 0.01913	청산 가격: 0.018948	return: 0.9904861474124411
[진입일: 1976-01-30] 진입 가격: 0.019859
[청산일: 1976-02-02] 진입 가격: 0.019859	청산 가격: 0.020041	return: 1.0091646105040535
[진입일: 1976-02-27] 진입 가격: 0.022045
[청산일: 1976-03-01] 진입 가격: 0.022045	청산 가격: 0.022227	return: 1.0082558403266046
[진입일: 1976-03-31] 진입 가격: 0.023898
[청산일: 1976-04-01] 진입 가격: 0.023898	청산 가격: 0.023898	return: 1.0
[진입일: 1976-04-30] 진입 가격: 0.020979
[청산일: 1976-05-03] 진입 가격: 0.020979	청산 가격: 0.020979	return: 1.0
[진입일: 1976-05-28] 진입 가격: 0.020067
[청산일: 1976-06-01] 진입 가격: 0.020067	청산 가격: 0.019155	return: 0.9545522499626251
[진입일: 1976-06-30] 진입 가격: 0.020097
[청산일: 1976-07-01] 진입 가격: 0.020097	청산 가격: 0.020462	return: 1.018161914713639
[진입일: 1976-07-30] 진입 가격: 0.017539
[청산일: 1976-08-02] 진입 가격: 0.017539	청산 가격: 0.01827	return: 1.0416785449569532
[진입일: 1976-08-31] 진입 가격: 0.021558
[청산일: 1976-09-01] 진입 가격: 0.021558	청산 가격: 0.021741	return: 1.0084887280823824
[진입일: 1976-09-30] 진입 가격: 0.022685
[청산일: 1976-10-01] 진입 가격: 0.022685	청산 가격: 0.02232	return: 0.9839100727352876
[진입일: 1976-10-29] 진입 가격: 0.020856
[청산일: 1976-11-01] 진입 가격: 0.020856	청산 가격: 0.020856	return: 1.0
[진입일: 1976-12-31] 진입 가격: 0.022724
[청산일: 1977-01-03] 진입 가격: 0.022724	청산 가격: 0.022174	return: 0.9757965146981165
[진입일: 1977-01-31] 진입 가격: 0.020341
[청산일: 1977-02-01] 진입 가격: 0.020341	청산 가격: 0.020525	return: 1.0090457696278452
[진입일: 1977-07-29] 진입 가격: 0.021547
[청산일: 1977-08-01] 진입 가격: 0.021547	청산 가격: 0.021731	return: 1.00853947185223
[진입일: 1977-09-30] 진입 가격: 0.025118
[청산일: 1977-10-03] 진입 가격: 0.025118	청산 가격: 0.025487	return: 1.0146906600844015
[진입일: 1977-10-31] 진입 가격: 0.024933
[청산일: 1977-11-01] 진입 가격: 0.024933	청산 가격: 0.024379	return: 0.9777804516103157
[진입일: 1977-11-30] 진입 가격: 0.0274
[청산일: 1977-12-01] 진입 가격: 0.0274	청산 가격: 0.029252	return: 1.0675912408759123
[진입일: 1977-12-30] 진입 가격: 0.029992
[청산일: 1978-01-03] 진입 가격: 0.029992	청산 가격: 0.029807	return: 0.9938316884502534
[진입일: 1978-01-31] 진입 가격: 0.028141
[청산일: 1978-02-01] 진입 가격: 0.028141	청산 가격: 0.028881	return: 1.0262961515226894
[진입일: 1978-02-28] 진입 가격: 0.028696
[청산일: 1978-03-01] 진입 가격: 0.028696	청산 가격: 0.029067	return: 1.012928631168107
[진입일: 1978-03-31] 진입 가격: 0.027856
[청산일: 1978-04-03] 진입 가격: 0.027856	청산 가격: 0.026741	return: 0.9599727168294084
[진입일: 1978-04-28] 진입 가격: 0.034541
[청산일: 1978-05-01] 진입 가격: 0.034541	청산 가격: 0.035469	return: 1.0268666222749776
[진입일: 1978-05-31] 진입 가격: 0.035655
[청산일: 1978-06-01] 진입 가격: 0.035655	청산 가격: 0.034727	return: 0.9739727948394336
[진입일: 1978-06-30] 진입 가격: 0.034805
[청산일: 1978-07-03] 진입 가격: 0.034805	청산 가격: 0.035178	return: 1.0107168510271511
[진입일: 1978-07-31] 진입 가격: 0.03648
[청산일: 1978-08-01] 진입 가격: 0.03648	청산 가격: 0.03648	return: 1.0
[진입일: 1978-08-31] 진입 가격: 0.040575
[청산일: 1978-09-01] 진입 가격: 0.040575	청산 가격: 0.040469	return: 0.9973875539125077
[진입일: 1978-09-29] 진입 가격: 0.041401
[청산일: 1978-10-02] 진입 가격: 0.041401	청산 가격: 0.042147	return: 1.0180188884326464
[진입일: 1978-10-31] 진입 가격: 0.033942
[청산일: 1978-11-01] 진입 가격: 0.033942	청산 가격: 0.035807	return: 1.0549466737375524
[진입일: 1978-11-30] 진입 가격: 0.034315
[청산일: 1978-12-01] 진입 가격: 0.034315	청산 가격: 0.034688	return: 1.0108698819758122
[진입일: 1978-12-29] 진입 가격: 0.034024
[청산일: 1979-01-02] 진입 가격: 0.034024	청산 가격: 0.033837	return: 0.9945038796143899
[진입일: 1979-01-31] 진입 가격: 0.033837
[청산일: 1979-02-01] 진입 가격: 0.033837	청산 가격: 0.034772	return: 1.0276324733280138
[진입일: 1979-02-28] 진입 가격: 0.034585
[청산일: 1979-03-01] 진입 가격: 0.034585	청산 가격: 0.035332	return: 1.0215989590863093
[진입일: 1979-03-30] 진입 가격: 0.036379
[청산일: 1979-04-02] 진입 가격: 0.036379	청산 가격: 0.036379	return: 1.0
[진입일: 1979-04-30] 진입 가격: 0.038067
[청산일: 1979-05-01] 진입 가격: 0.038067	청산 가격: 0.038254	return: 1.0049123913100588
[진입일: 1979-05-31] 진입 가격: 0.038254
[청산일: 1979-06-01] 진입 가격: 0.038254	청산 가격: 0.038629	return: 1.0098028964291315
[진입일: 1979-06-29] 진입 가격: 0.037987
[청산일: 1979-07-02] 진입 가격: 0.037987	청산 가격: 0.036858	return: 0.9702793060783953
[진입일: 1979-07-31] 진입 가격: 0.039115
[청산일: 1979-08-01] 진입 가격: 0.039115	청산 가격: 0.039491	return: 1.0096126805573309
[진입일: 1979-09-28] 진입 가격: 0.048058
[청산일: 1979-10-01] 진입 가격: 0.048058	청산 가격: 0.047681	return: 0.9921553123309336
[진입일: 1979-10-31] 진입 가격: 0.044477
[청산일: 1979-11-01] 진입 가격: 0.044477	청산 가격: 0.044854	return: 1.0084762911167569
[진입일: 1979-11-30] 진입 가격: 0.052769
[청산일: 1979-12-03] 진입 가격: 0.052769	청산 가격: 0.053146	return: 1.0071443461123006
[진입일: 1979-12-31] 진입 가격: 0.050234
[청산일: 1980-01-02] 진입 가격: 0.050234	청산 가격: 0.050612	return: 1.0075247840108292
[진입일: 1980-01-31] 진입 가격: 0.053823
[청산일: 1980-02-01] 진입 가격: 0.053823	청산 가격: 0.053634	return: 0.9964884900507218
[진입일: 1980-02-29] 진입 가격: 0.048346
[청산일: 1980-03-03] 진입 가격: 0.048346	청산 가격: 0.047024	return: 0.9726554420220909
[진입일: 1980-03-31] 진입 가격: 0.043207
[청산일: 1980-04-01] 진입 가격: 0.043207	청산 가격: 0.044533	return: 1.030689471613396
[진입일: 1980-04-30] 진입 가격: 0.049271
[청산일: 1980-05-01] 진입 가격: 0.049271	청산 가격: 0.050597	return: 1.0269123825373951
[진입일: 1980-05-30] 진입 가격: 0.051924
[청산일: 1980-06-02] 진입 가격: 0.051924	청산 가격: 0.051166	return: 0.9854017410060859
[진입일: 1980-06-30] 진입 가격: 0.05833
[청산일: 1980-07-01] 진입 가격: 0.05833	청산 가격: 0.05776	return: 0.990228013029316
[진입일: 1980-07-31] 진입 가격: 0.06669
[청산일: 1980-08-01] 진입 가격: 0.06669	청산 가격: 0.06555	return: 0.9829059829059829
[진입일: 1980-08-29] 진입 가격: 0.073491
[청산일: 1980-09-02] 진입 가격: 0.073491	청산 가격: 0.07311	return: 0.9948156917173531
[진입일: 1980-09-30] 진입 가격: 0.076156
[청산일: 1980-10-01] 진입 가격: 0.076156	청산 가격: 0.079964	return: 1.0500026261883502
[진입일: 1980-10-31] 진입 가격: 0.076918
[청산일: 1980-11-03] 진입 가격: 0.076918	청산 가격: 0.076537	return: 0.9950466730804233
[진입일: 1980-11-28] 진입 가격: 0.085676
[청산일: 1980-12-01] 진입 가격: 0.085676	청산 가격: 0.086628	return: 1.011111629861338

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().